### ISSUE TITLE
Hexo-Aurora开启配置gitalk

### ISSUE THREAD

**Issue by znicelya** [znicelya/znicelya.github.io#18]
https://blog.nicely.fun/post/Hexo-Aurora%E5%BC%80%E5%90%AF%E9%85%8D%E7%BD%AEgitalk 
 Hexo-Aurora开启配置gitalkRepo首先去Github新建一个仓库 自行填写仓库信息 建完之后先放着，等会儿后面会用到 Token登录GitHub 点击右上角 转到设置页面，往下拉，找到 开发者设置 新建一个OAuth App 记住 clientID 和 secre...

**Comment by jankin12138** [comment]
您好请问每篇文章应该如何设置图片啊

**Comment by znicelya** [comment]
在文章头部加上cover： [图片网络地址]

**Comment by znicelya** [comment]
> @jankin12138
> 您好请问每篇文章应该如何设置图片啊

在文章头部加上cover: [图片网络地址]

**Comment by xiaomait** [comment]
同样的步骤为何一直显示 Error: Validation Failed.
