### ISSUE TITLE
Hexo+Aurora+COS+CDN

### ISSUE THREAD

**Issue by znicelya** [znicelya/znicelya.github.io#9]
http://blog.nicely.fun/post/Hexo-Aurora-Cos-CDN 
 Hexo+Aurora+COS+CDNGit安装 Windows 访问官网 https:&#x2F;&#x2F;git-scm.com&#x2F; 直接安装即可 若速度太慢可访问国内淘宝镜像 https:&#x2F;&#x2F;registry.npmmirror.com&#x2...

**Comment by YuGepro** [comment]
感谢博主制作的教程！

**Comment by Luwu-ora** [comment]
为啥我按步骤来页面还是没反应，主要是cp -rf ./node_modules/hexo-theme-aurora/_config.yml ./_config.aurora.yml
的时候，教程上_config.yml从2541 Feb变成了和_config.aurora.yml相同的4852 Feb，但我的还是2541 Feb，不知道是不是因为这个

**Comment by znicelya** [comment]
> @Luwu-ora
> 为啥我按步骤来页面还是没反应，主要是cp -rf ./node_modules/hexo-theme-aurora/_config.yml ./_config.aurora.yml
> 的时候，教程上_config.yml从2541 Feb变成了和_config.aurora.yml相同的4852 Feb，但我的还是2541 Feb，不知道是不是因为这个

也可以直接去node_modules/hexo-theme-aurora下面手动复制粘贴过来

**Comment by ming-liu163** [comment]
> @znicelya
> > @Luwu-ora
> > 为啥我按步骤来页面还是没反应，主要是cp -rf ./node_modules/hexo-theme-aurora/_config.yml ./_config.aurora.yml
> > 的时候，教程上_config.yml从2541 Feb变成了和_config.aurora.yml相同的4852 Feb，但我的还是2541 Feb，不知道是不是因为这个
> 
> ###### 也可以直接去node_modules/hexo-theme-aurora下面手动复制粘贴
> ###### 我上面图上错了应该是复制 **_config.aurora.yml**
不不，复制的操作是对了的，只是后面有个东西需要改，那个config.yml中的theme需要aurora.

**Comment by ZiFeiYu987** [comment]
小白提问：这个Cos到期以后是要缴费是吗？

**Comment by pandaxgc** [comment]
自2022年5月9日起，对象存储（Cloud Object Storage，COS）服务将不再支持新增默认 CDN 加速域名

**Comment by Grooveboox** [comment]
> @ming-liu163
> > @znicelya
> > > @Luwu-ora
> > > 为啥我按步骤来页面还是没反应，主要是cp -rf ./node_modules/hexo-theme-aurora/_config.yml ./_config.aurora.yml
> > > 的时候，教程上_config.yml从2541 Feb变成了和_config.aurora.yml相同的4852 Feb，但我的还是2541 Feb，不知道是不是因为这个
> > 
> > ###### 也可以直接去node_modules/hexo-theme-aurora下面手动复制粘贴
> > ###### 我上面图上错了应该是复制 **_config.aurora.yml**
> 不不，复制的操作是对了的，只是后面有个东西需要改，那个config.yml中的theme需要aurora.
> 

谢谢你

**Comment by Grooveboox** [comment]
感谢博主制作的教程！

**Comment by LuiYang08** [comment]
> @aCleverFish
> 博主能不能分享一下aurora配gitalk改哪些配置，自己一直配不好，会出错

同问，gitalk都不知道怎么设置

**Comment by znicelya** [comment]
> @LuiYang08
> > @aCleverFish
> > 博主能不能分享一下aurora配gitalk改哪些配置，自己一直配不好，会出错
> 
> 同问，gitalk都不知道怎么设置

新出了一份gitalk配置教程 https://blog.nicely.fun/post/Hexo-Aurora%E5%BC%80%E5%90%AF%E9%85%8D%E7%BD%AEgitalk
